### ISSUE TITLE
Small error in documentation about importing CWE

### ISSUE THREAD

**Issue by athivillon** [aatlasis/cve_manager#2]
The PDF file states :

```
./cve_manager.py -u <username> -ps <password> -server <IP or hostname of
dababase server> -db <name of database> -cwe 1000.csv
```

The real option is -icwe or --import_cwe  instead of -cwe

This is a real useful tool, thank you for your work.

**Comment by aatlasis** [comment]
Fixed; thank you for pointing this out.
