### ISSUE TITLE
Windows: Error e 'charmap' codec can't encode character '\u2264' in position 258

### ISSUE THREAD

**Issue by chaithubk** [aatlasis/cve_manager#3]
I have executed the script on Windows machine
`python cve_manager.py -p -csv `

... and I have noticed an error while processing 2002 NIST NVD download, as mentioned below: 

```
Processing nvdcve-1.1-2002.json.zip
CVE_data_timestamp: 2020-07-29T09:08Z
CVE_data_version: 4.0
CVE_data_format: MITRE
CVE_data_number of CVEs: 6748
CVE_data_type: CVE
Error e 'charmap' codec can't encode character '\u2264' in position 258: character maps to <undefined>           
```                 

However the same script worked fine on the Ubuntu machine. Is this script compatible on Windows ?

**Comment by 0xsuid** [comment]
@aatlasis Issue fixed by PR #5
