### ISSUE TITLE
Error when populating posgres from sve_cvss_scores.csv

### ISSUE THREAD

**Issue by idimou** [aatlasis/cve_manager#7]
cve_manager.py", line 316, in process_cves
    cur.copy_from(output, 'cvss', sep='\t', null="")
psycopg2.errors.BadCopyFileFormat: missing data for column "attack_complexity_3"

First line in sve_cvss_scores.csv seems to be missing delimiters and therefore is not parsed correctly when mapping to postgres columns.

**Comment by fmgomes** [comment]
How did you solve the problem? I have downloaded today the code and I have the same problem -  psycopg2.errors.BadCopyFileFormat: missing data for column "attack_complexity_3"
I'm running it on windows and it seems related to having a blank line in the CVS file between each line. But deleting the blank line I only replace the error in column "attack_complexity_3" with column "problem"

**Comment by sandadaami** [comment]
i have the same problem  i don't know how i solve it 
File "C:\Users\SANDA\Downloads\cve_manager-master\cve_manager.py", line 344, in process_cves
    cur.copy_from(output,'cvss', sep='\t',null="")
psycopg2.errors.BadCopyFileFormat: ERREUR:  données manquantes pour la colonne « attack_complexity_3 »
CONTEXT:  COPY cvss, ligne 1 : «  »
